package vedant.learningPhase;

public class BankAccount {
    private String number;
    private double balance;
    private String customerName;
    private String email;
    private String phoneNumber;

    public BankAccount(){
         this("null","null",0.00, "null","null");        // just , when empty constructor called, and
        // not fill value manually in main then we will see these default values as execution.
        System.out.println("Empty Constructor is called");
    }



    // this is created filled constructor......
    public BankAccount(String customerName, String number, double balance, String email, String phoneNumber){
        System.out.println("Filled Constructor is called");
        this.customerName = customerName;
        this.number =number;
        this.balance =balance;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }

    // create another constructor which can take two value by default and update other information;
    public BankAccount(String customerName, String email, String phoneNumber) {
        this(customerName, "99999", 100.50, email, phoneNumber);
    }


        // add two method from our side for transactions.
    public void deposit(double depositAmount){
        this.balance += depositAmount;
        System.out.println("deposited Amount = "+ depositAmount);
        System.out.println("New balance = " + balance);
        System.out.println(" ");
        System.out.println(" Thank you for visiting US!");
        System.out.println(" ");
    }

    public void withdraw(double withdrawAmount){
        if (balance < withdrawAmount){
            System.out.println("The Transaction is not possible, you balance is " + balance + " which is " + (withdrawAmount-balance) + " less.");
            System.out.println(" ");
        } else {
            this.balance -= withdrawAmount;
            System.out.println("Withdraw is completed of amount = " + withdrawAmount);
            System.out.println(" The New balance = " + balance);
            System.out.println(" ");
        }
        System.out.println("Thank you for visiting US!");
        System.out.println(" ");
    }

    // following method generated by ... Code >> generator >> setter & getter >> OK...

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}
